bootstrap.servers=kafka:19092
group.id=workshop-connect-cluster

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

config.storage.topic=workshop-connect-configs
config.storage.replication.factor=1
offset.storage.topic=workshop-connect-offsets
offset.storage.replication.factor=1
status.storage.topic=workshop-connect-status
status.storage.replication.factor=1
offset.flush.interval.ms=1000

plugin.path=/opt/kafka/plugins
rest.host.name=0.0.0.0
rest.port=8083
rest.advertised.host.name=connect
rest.advertised.port=8083
